
export const GET_REPOSITORY_EXECUTING  = "GET_REPOSITORY_EXECUTING";
export const GET_REPOSITORY_SUCCESS    = "GET_REPOSITORY_SUCCESS";
export const GET_REPOSITORY_FAIL       = "GET_REPOSITORY_FAIL";
export const SET_REPOSITORY_SELECTED_ITEM = "SET_REPOSITORY_SELECTED_ITEM"
